address: "127.0.0.1"
port: "8081"
ratelimit: 20

Redis:
  port: 6379

HackerNews:
  url: http://hn.algolia.com/api/v1/search

Github:
  url: https://api.github.com/search/repositories

StackOverflow:
  url: https://api.stackexchange.com/2.2/search/advanced
